modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/drewburr/minecraft-prometheus-exporter/issues"

[[mods]]
modId = "prometheus_exporter"
version = "${version}"
displayName = "Prometheus Exporter"
description = '''${mod_description}'''
authors = "drewburr, cpburnz"
displayURL = "https://github.com/drewburr/minecraft-prometheus-exporter"

[[dependencies.prometheus_exporter]]
modId = "neoforge"
type = "required"
versionRange = "[26,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.prometheus_exporter]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,27)"
ordering = "NONE"
side = "SERVER"
